### ISSUE TITLE
Link to 'Edit on github' leads to 404

### ISSUE THREAD

**Issue by codams** [SaraVieira/gatsby-starter-book#14]
On the index doc page, the 'Edit on github' fails to a 404 (https://github.com/SaraVieira/starter-book/tree/docsREADME.md) but the github icon link works fine.

Hope it's usefull, have a great day !

**Comment by codams** [comment]
Just check in index.js, it seems somewhere the README.md part is added

**Comment by SaraVieira** [comment]
Closed by #14
